### PR TITLE
Order details fixes and improvements

### PR DESCRIPTION
**Pull request by CarlosOrdering**

### CODE REVIEW

**Comment by quirozcarlos** [comment]
@CarlosOrdering pls provide some screenshots/videos to display the result

**Comment by CarlosOrdering** [comment]
Remove Ordering logo before: https://d.pr/i/GzoEoM after https://d.pr/i/GzoEoM
If customer have an active order, the card stretch and don't show the info, before: https://d.pr/i/5zaSya after: https://d.pr/i/GPBts2
Phone button now open the default phone app: https://d.pr/v/HUC81j
On review, stars where preselected and not of main color: https://d.pr/i/cnU6VN after: https://d.pr/v/Vsl5vQ

**Comment by quirozcarlos** [comment]
@CarlosOrdering I think you should hide the image on the right when the width is less than 480px
image

**Comment by CarlosOrdering** [comment]
This is the change: https://d.pr/v/oZbln3

**Comment by quirozcarlos** [comment]
Nice job!

**Pull request merged**
